name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up SSH Key
      shell: bash
      run: |
        echo "${{ secrets.EC2_KEY }}" > ~/hello_world.pem
        chmod 400 ~/hello_world.pem

    - name: Deploy Code
      shell: bash
      run: |
        # Copy all project files to the EC2 instance
        scp -o StrictHostKeyChecking=no -i ~/hello_world.pem -r ./hello_world/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/hello_world/
        
        # SSH into the EC2 instance and deploy
        ssh -o StrictHostKeyChecking=no -i ~/hello_world.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          cd /home/${{ secrets.EC2_USER }}/hello_world &&
          sudo docker-compose up --build -d
        "